travis:
  secure:
    BINSTAR_TOKEN: MNK6kRwqu+/RfJNBsPfUQXn1nZ5m4tlWNOy00JbLOAiWavdFzsGqTBEckGTd6PYcuCA+mKg7YspQRMjLciProI91vllQ/Ysup26my5bAlyxxIlwiOPXtAHLtm0Rn6D5KRIjGX9xoqMTDO5DuCAxf0Bgu6rvhVYuDuCXK0hMJZr014CM75gVnvSPP7Vp9ECz+xW/EQkSHk5dOq2ziM0hLOhQUW/i1L2tUWSDwCLLHVfGO6fbyGRry8Y0Yf5KBS3dkX3sznTrU2AbgcqPx+yTeRloqgvmF0opf3DCGIKDSVqQy8IkpJdslBVHrnavKhyHq13vFbHtcly9a739iXjXWMgmUILhGpleNAATY17zNlwKioipDfOP1fjhFowtHqPH635x0/xQIbcWUqCzyKFUvF7yC3Iu225dOZGMpFV7uX9GYAkV4vCh+EjWbN5/g/y2Aes3U0O7I1U57XcAUQ0AZnY+VH8doBWTc9W7F3oC2441c/BWc04Abvd61uhCZcHlYZOzRdnbn4F3LJvIrzLnuNczAz0cjjXrTPLGK7/uxg+6MABeoqW2jbFAgcTZAn9GmbwaPcLoMrU3Ry1MC3ZYpQ0xPZuE47RSLNTPigvUYzFnGRpJcj6YclpD9k+inLlImqf4rkDy6kcc+YGMntcadRTm97wM57ARdwrwBDWHYFag=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
